version: '2'
services:
  megafuse:
    environment: 
      - PASSPHRASE
      - VOLSIZE
      - OLDERTHAN
      - TZ
      - RESTOREDPATH
    hostname: ${HOSTNAME}
    privileged: true
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./.env:/root/megafuse.conf:ro
      - ./cache:/root/.cache/duplicity:rw
      - ./configs:/root/configs:ro
      - $RESTOREDPATH:/root/megarestored:rw
      - /:/hostdisk:ro
    dns:
      - 169.254.1.3
    stdin_open: true
    tty: true
    container_name: megafuse
    command: MegaFuse -c /root/megafuse.conf
    command:  >
      sh -c "ln -snf /usr/share/zoneinfo/$TZ /etc/localtime && 
      echo $TZ > /etc/timezone &&
      exec MegaFuse -c /root/megafuse.conf"
    restart: always
